FORMAT: 1A
HOST: http://wombat.ryu.titech.ac.jp/natsume-server

# natsume-server
natsume-serverはユーザ入力を解析し、一般的にJSONで返答する。

# Group Sources



## Sources summary [GET /api/sources]

Returns general information on the corpora and documents included in Natsume.

+ Request (application/json)

+ Response 200 (application/json)

### Genre [GET /api/sources/genre]

+ Parameters

    + norm (optional, string, `sentences|paragraphs|sources`) ... The normalization level used for counts.

+ Model (application/json)

    ```
    {
      "children" : [
      {
         "count" : 252,
         "name" : "韻文",
         "children" : [
            {
               "count" : 100,
               "name" : "詩"
            },
            {
               "count" : 60,
               "name" : "短歌"
            },
            {
               "count" : 92,
               "name" : "俳句"
            }
         ]
      },
      {
        ...
      },
      {
         "name" : "Wikipedia",
         "count" : 853975
      }
   ],
   "count" : 1027389,
   "name" : "Genres"
}
    ```

### Similarity [GET /api/sources/genre/similarity]


# Group Tokens [GET /api/tokens]

+ Parameters

    + id (required, string, `123`) ... The id of the Person.

+ Model (application/json)

    ```
    {}
    ```

# Group Collocations [GET /api/collocations]

+ Parameters

    + id (required, string, `123`) ... The id of the Person.

+ Model (application/json)

    ```
    {}
    ```

## Collocation tree [GET /api/collocations/tree]

+ Parameters

    + id (required, string, `123`) ... The id of the Person.

+ Model (application/json)

    ```
    {}
    ```